
CREATE TABLE tipos_documento (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre_tipo TEXT NOT NULL,
  descripcion TEXT,
  is_activo BOOLEAN DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
